apiVersion: v2
name: loki-lgtm-stack
description: A wrapper chart for loki
type: application
version: 1.0.0
appVersion: "17.4.0"

dependencies:
  - name: loki-distributed
    version: "17.4.0" # Or your preferred version
    repository: "https://grafana-community.github.io/helm-charts"