tempoGateway:
  enabled: false
tempo:
  nodeSelector:
    karpenter.sh/capacity-type: on-demand # Tempo is stateful and should run on stable on-demand instances
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "gp3-automode-eks-dev"
  multitenancyEnabled: true # Enable multitenancy with a X-Scope-OrgID Header
  reportingEnabled: false #Disable reporting to Grafana Labs , prevent outgoing traffic
