{{- if .Values.tempoGateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-tempo-gateway" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | default "observability" }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.tempoGateway.parentGatewayName | quote }}
      namespace: {{ .Values.tempoGateway.parentGatewayNamespace | default .Release.Namespace | quote }}
  # Only render hostnames if the list is provided and not empty
  {{- if .Values.tempoGateway.hostnames }}
  hostnames:
    {{- range .Values.tempoGateway.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            # Defaults to / if no path is provided
            value: {{ .Values.tempoGateway.path | default "/" | quote }}
      # Rewrite filter logic
      {{- if and .Values.tempoGateway.path (ne .Values.tempoGateway.path "/") }}
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
      {{- end }}
      
      backendRefs:
        - name: tempo-gateway
          port: {{ .Values.tempoGateway.servicePort | default 80 }}
{{- end }}
